name: test

on:
  pull_request:
  push: { branches: main }

jobs:

  run-test:
    runs-on: ubuntu-20.04
    timeout-minutes: 20

    strategy:
      matrix:
        postgres: [15]

    steps:
      - uses: actions/checkout@v3

      - name: checkout hypopg
        uses: actions/checkout@v3
        with:
          repository: 'HypoPG/hypopg'
          ref: 'debian/1.3.1-2'
          path: ./hypopg

      - name: run tests
        run: |
          apt-get update && apt-get install build-essential postgresql-server-dev-${{ matrix.postgres }} -y

          # Ensure installed pg_config is first on path
          export PATH=$PATH:/usr/lib/postgresql/${{ matrix.postgres }}/bin

          cd hypopg
          make
          make install

          # Install index_advisor
          cd ..
          make
          make install

          # Run tests
          make installcheck

          cat regression.out
