name: test

on:
  pull_request:
  push: { branches: main }

jobs:
  run-test:
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    timeout-minutes: 20

    strategy:
      matrix:
        postgres: [15]

    steps:
      - name: Start PostgreSQL ${{ matrix.pg }}
        run: pg-start ${{ matrix.pg }}

      - name: Install build-dependencies
        run: apt-get install -y liblz4-dev libreadline-dev zlib1g-dev libzstd-dev

      - uses: actions/checkout@v3

      - name: checkout hypopg
        uses: actions/checkout@v3
        with:
          repository: 'HypoPG/hypopg'
          ref: 'debian/1.3.1-2'
          path: ./hypopg

      - name: Create tests directory
        run: sudo -u postgres mkdir /tmp/tests

      - name: Create tests tablespace
        run: sudo -u postgres psql -c "CREATE TABLESPACE testts LOCATION '/tmp/tests'"

      - name: Create Database
        run: sudo -u postgres psql -c 'CREATE DATABASE contrib_regression;'

      - name: install hypopg
        run: |
          cd hypopg
          sudo make install
          cd ..

      - name: Test index-advisor on PG-${{ matrix.pg }}
        run: pg-build-test

      - name: Show regression.diffs
        if: ${{ failure() }}
        run: cat regress/regression.diffs

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: regression.out
          path: regression.out
          retention-days: 7
